#! /bin/sh
#__________________________________________________
#  ██                                              |
# ░██              ██████                          |
# ░██       ██████░██░░░██ ███     ██ ██████████   |
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██  |
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██  |
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██  |
# ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██  |
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░   |
#           github.com/JuanToledoCol               |
#__________________________________________________|

#Picom
pkill picom
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &

#Skhkd
pgrep -x sxhkd > /dev/null || sxhkd &

#Launch Dunst
pkill dunst
dunst -conf ~/.config/dunst/dunstrc &

#Polybar
$HOME/.config/polybar/launch.sh --shapes &
# polybar &

#Script for battery
$HOME/.config/verifyBattery.sh &
#Script for popups
$HOME/.config/popups.sh &

#Wifi
nm-applet &

bspc monitor -d I II III IV V 
bspc config top_padding 26
bspc config border_width         2
bspc config window_gap		 8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
xsetroot -cursor_name left_ptr -xcf 32 32 /usr/share/icons/Bibata-Modern-Classic/cursors/left_ptr

bspc rule -a Thunar state=floating
bspc rule -a Thunar state=floating rectangle=800x600+$((($(bspc query -M --names-width) - 800) / 2))+$((($(bspc query -m --names-height) - 600) / 2))

# Keyboard
setxkbmap latam &
#Tools-----------
flameshot &
#Wallpaper-------
feh --bg-scale /home/juarch/Pictures/wallhaven-zx12wj_1920x1080.png &
